server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # para el routing de Angular
    }

    location /api/ {
        proxy_pass http://api-vivero:8080;  # nombre del contenedor backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}